import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ghazi Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="display w-full h-[100vh] mt-3  flex flex-col md:flex-row">
          <div className="w-full md:w-[25%]  bg-secondary ">
            <Sidebar/>
          </div>
          <div className="w-full md:w-[75%] flex flex-col">
            <div className="overflow-auto h-[100%] scrollbar-custom ">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
